### ISSUE TITLE
Unable to install "heroku pluins:install java"

### ISSUE THREAD

**Issue by MattGurney** [heroku/plugin-java#8]
myUser1@ % heroku --version
heroku/7.42.1 darwin-x64 node-v12.16.2

myUser1@  % heroku plugins                       
no plugins installed

myUser1@  % heroku plugins:install java          
error /Users/myUser1/.local/share/heroku/node_modules/java: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments: 
Directory: /Users/myUser1/.local/share/heroku/node_modules/java
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@7.0.0
gyp info using node@12.16.2 | darwin | x64
gyp info find Python using Python version 3.7.3 found at "/Applications/Xcode.app/Contents/Developer/usr/bin/python3"
gyp info spawn /Applications/Xcode.app/Contents/Developer/usr/bin/python3
gyp info spawn args [
gyp info spawn args   '/Users/myUser1/.config/yarn/global/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/myUser1/.local/share/heroku/node_modules/java/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/myUser1/.config/yarn/global/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/myUser1/Library/Caches/node-gyp/12.16.2/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/myUser1/Library/Caches/node-gyp/12.16.2',
gyp info spawn args   '-Dnode_gyp_dir=/Users/myUser1/.config/yarn/global/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/myUser1/Library/Caches/node-gyp/12.16.2/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/myUser1/.local/share/heroku/node_modules/java',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  CXX(target) Release/obj.target/nodejavabridge_bindings/src/java.o
In file included from ../src/java.cpp:1:
In file included from ../src/java.h:7:
/Users/myUser1/Library/Java/JavaVirtualMachines/openjdk-14.0.1/Contents/Home/include/jni.h:45:10: fatal error: 'jni_md.h' file not found
#include "jni_md.h"
         ^~~~~~~~~~
1 error generated.
make: *** [Release/obj.target/nodejavabridge_bindings/src/java.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/myUser1/.config/yarn/global/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:310:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Darwin 19.5.0
gyp ERR! command "/Users/myUser1/.local/share/heroku/client/7.42.1/bin/node" "/usr/local/bin/node-gyp" "rebuild"
gyp ERR! cwd /Users/myUser1/.local/share/heroku/node_modules/java
gyp ERR! node -v v12.16.2
gyp ERR! node-gyp -v v7.0.0
gyp ERR! not ok
Installing plugin java... !

**Comment by Malax** [comment]
Thanks for opening the issue! We're working on a fix. As a workaround, installing the plugin should work with `heroku plugins:install @heroku-cli/plugin-java` should work as expected.

**Comment by Malax** [comment]
The workaround above is no longer necessary. `heroku plugins:install java` should work again. 

@MattGurney if you continue to have problems, feel free to comment in this issue.
